<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Crear 1' => 'Crear 1',
    'Crear más de 1' => 'Crear máis de 1',
    'Crear socios' => 'Crear socios',
    'Error en el servidor' => 'Erro no servidor',
    'Error: %s' => 'Erro: %s',
    'Fichero Excel' => 'Arquivo Excel',
    'Guardando...' => 'Gardando...',
    'Importar' => 'Importar',
    'Importar socios' => 'Importar socio',
    'Importar socios desde un excel' => 'Importar socio desde un excel',
    'Los socios se han importado correctamente' => 'Os socios foron importados correctamente',
    'Mensaje' => 'Mensaxe',
    'Socio %d actualizado' => 'Socio %d actualizado',
    'Socio %d creado' => 'Socio %d creado',
    'Borrar' => 'Borrar',
    'Datos de acceso' => 'Datos de acceso',
    'Expira' => 'Expira',
    'Fecha' => 'Data',
    'Fecha Alta' => 'Data Alta',
    'Id Socio' => 'Id Socio',
    'Nueva' => 'Nova',
    'Nuevo' => 'Novo',
    'Socio' => 'Socio',
    'Ver' => 'Ver',
    'Apellidos' => 'Apelidos',
    'Cancelar' => 'Cancelar',
    'Contraseña' => 'Contrasinal',
    'DNI' => 'DNI',
    'Editar' => 'Editar',
    'El socio no se ha podido borrar' => 'Non foi posible borrar o socio',
    'El socio se ha borrado correctamente' => 'O socio foi borrado correctamente',
    'El socio se ha guardado correctamente' => 'O socio foi gardado correctamente',
    'El usuario o la contraseña no son correctos' => 'O usuario ou o contrasinal non son correctos',
    'Email' => 'Email',
    'Entrar' => 'Entrar',
    'Error' => 'Erro',
    'Ese socio no existe' => 'Ese socio non existe',
    'Fecha de alta' => 'Data de alta',
    'Guardar' => 'Gardar',
    'No se ha podido guardar el socio' => 'Non foi posible gardar o socio',
    'No se ha podido guardar el socio: %s' => 'Non foi posible gardar o socio: %s',
    'Nombre' => 'Nome',
    'Nombre completo' => 'Nome completo',
    'Nombre de usuario' => 'Nome de usuario',
    'Nombre de usuario o Email' => 'Nome de usuario ou Email',
    'Notas' => 'Notas',
    'Nueva contraseña' => 'Novo contrasinal',
    'Nuevo socio' => 'Novo socio',
    'Nº de Socio' => 'Nº de Socio',
    'OK' => 'OK',
    'Recuérdame' => 'Recórdame',
    'Salir ({usuario})' => 'Saír ({usuario})',
    'Socio #%s desde el %s' => 'Socio #%s desde o %s',
    'Socios' => 'Socios',
    'Tienes que loguearte para poder entrar' => 'Tes que estar logueado para poder entrar',
    'Todos' => 'Todos',
    'Todos los socios' => 'Todos os socios',
    '¿Estás seguro de que quieres borrar este socio?' => 'Estás seguro de que queres borrar este socio?',
];
