<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Sobra algún dígito en el <b>DNI</b>' => 'Sobra algún díxito no <b>DNI</b>',
    'Sobra algún dígito en el <b>DNI</b> de {socio}' => 'Sobra algún díxito no <b>DNI</b> de {socio}',
    'Salir ({usuario})' => '@@Saír ({usuario})@@',
    'Advertencia' => 'Advertencia',
    'Apellidos' => 'Apelidos',
    'Campo' => 'Campo',
    'Cancelar' => 'Cancelar',
    'Contraseña' => 'Contrasinal',
    'Crear 1' => 'Crear 1',
    'Crear más de 1' => 'Crear máis de 1',
    'Crear socios' => 'Crear socios',
    'DNI' => 'DNI',
    'Datos de acceso a la aplicación' => 'Datos de acceso á aplicación',
    'Datos del socio' => 'Datos do socio',
    'Editar' => 'Editar',
    'El <b>DNI</b> no tiene letra' => 'O <b>DNI</b> non ten letra',
    'El socio no se ha podido borrar' => 'Non foi posible borrar o socio',
    'El socio se ha borrado correctamente' => 'O socio foi borrado correctamente',
    'El socio se ha guardado correctamente' => 'O socio foi gardado correctamente',
    'El usuario o la contraseña no son correctos' => 'O usuario ou o contrasinal non son correctos',
    'Email' => 'Email',
    'Entrar' => 'Entrar',
    'Error' => 'Erro',
    'Error en el servidor' => 'Erro no servidor',
    'Error: %s' => 'Erro: %s',
    'Errores' => 'Erros',
    'Errores en los socios' => 'Erros nos socios',
    'Ese socio no existe' => 'Ese socio non existe',
    'Falta algún dígito en el <b>DNI</b>' => 'Falta algún díxito no <b>DNI</b>',
    'Falta algún dígito en el <b>DNI</b> de {socio}' => 'Falta algún díxito no <b>DNI</b> de {socio}',
    'Falta la letra en el <b>DNI</b> de {socio}' => 'Falta a letra no <b>DNI</b> de {socio}',
    'Fecha de alta' => 'Data de alta',
    'Fichero Excel' => 'Arquivo Excel',
    'Guardando...' => 'Gardando...',
    'Guardar' => 'Gardar',
    'Importar' => 'Importar',
    'Importar socios' => 'Importar socio',
    'Importar socios desde un excel' => 'Importar socio desde un excel',
    'La letra del <b>DNI</b> de {socio} no es correcta' => 'A letra do <b>DNI</b> de {socio} non é correcta',
    'La letra del <b>DNI</b> es incorrecta' => 'A letra do <b>DNI</b> é incorrecta',
    'La letra del DNI debería ser {letra}' => 'A letra do DNI debería ser o {letra}',
    'Los socios se han importado correctamente' => 'Os socios foron importados correctamente',
    'Mensaje' => 'Mensaxe',
    'No se ha podido guardar el socio' => 'Non foi posible gardar o socio',
    'No se ha podido guardar el socio: %s' => 'Non foi posible gardar o socio: %s',
    'No tiene <b>DNI</b>' => 'Non ten <b>DNI</b>',
    'No tiene <b>apellidos</b>' => 'Non ten <b>apelidos</b>',
    'No tiene <b>nombre</b>' => 'Non ten <b>nome</b>',
    'Nombre' => 'Nome',
    'Nombre completo' => 'Nome completo',
    'Nombre de usuario' => 'Nome de usuario',
    'Nombre de usuario o Email' => 'Nome de usuario ou Email',
    'Notas' => 'Notas',
    'Nueva contraseña' => 'Novo contrasinal',
    'Nuevo socio' => 'Novo socio',
    'Nº Socio' => 'Nº Socio',
    'Nº de Socio' => 'Nº de Socio',
    'OK' => 'OK',
    'Recuérdame' => 'Recórdame',
    'Salir' => 'Saír',
    'Socio %d actualizado' => 'Socio %d actualizado',
    'Socio %d actualizado pero la letra del DNI debería ser la %s' => 'Socio %d actualizado pero a letra do DNI debería ser o %s',
    'Socio %d creado' => 'Socio %d creado',
    'Socio %d creado pero la letra del DNI debería ser la %s' => 'Socio %d creado pero a letra do DNI debería ser o %s',
    'Socios' => 'Socios',
    'Tienes que loguearte para poder entrar' => 'Tes que estar logueado para poder entrar',
    'Todos' => 'Todos',
    'Todos los socios' => 'Todos os socios',
    '{socio1} y {socio2} tienen el mismo <b>DNI</b>' => '{socio1} e {socio2} teñen o mesmo <b>DNI</b>',
    '{socio} no tiene <b>DNI</b>' => '{socio} non ten <b>DNI</b>',
    '{socio} no tiene <b>apellidos</b>' => '{socio} non ten <b>apelidos</b>',
    '{socio} no tiene <b>nombre</b>' => '{socio} non ten <b>nome</b>',
    '¿Estás seguro de que quieres borrar este socio?' => 'Estás seguro de que queres borrar este socio?',
];
